[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
]

[project.scripts]
cela = "cela:main"

[tool.setuptools]
py-modules = ["cela", "config", "debug"]
packages = ["main", "cellular_automaton", "randomisation"]
